=== abpelegrina/violet-owl/trunk/violet-owl-2/org/ugr/violet/persistance/project.dtd
<!ELEMENT project (ontologies, diagrams) >
<!ATTLIST project name NMTOKEN #REQUIRED>

<!ELEMENT ontologies (ontology*) >
<!ELEMENT ontology EMPTY>
<!ATTLIST ontology id ID #REQUIRED uri CDATA #REQUIRED name NMTOKEN #REQUIRED>

<!ELEMENT diagrams (diagram*) >
<!ELEMENT diagram (node+, edge+) >
<!ATTLIST diagram id ID #REQUIRED type NMTOKEN #REQUIRED>
<!ELEMENT node EMPTY>
<!ELEMENT edge EMPTY>
<!ATTLIST edge id ID #REQUIRED type NMTOKEN #REQUIRED name NMTOKEN #REQUIRED source IDREFS #REQUIRED dest IDREFS #REQUIRED>
<!ATTLIST node id ID #REQUIRED type NMTOKEN #REQUIRED name NMTOKEN #REQUIRED>

=== abpelegrina/violet-owl/trunk/violet-owl/org.protege.editor.owl.example.tab/build/classes/build/classes/org/ugr/ontology/persistance/ejemploProyecto.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project SYSTEM "project.dtd">
<project name="UnProyecto">
	<ontologies>
		<ontology name='unaOntologia' uri='http://www.ugr.es' id='zdjf'  />
	</ontologies>
	<diagrams>
		<diagram id='c' type='sfadsf'>
			<node id='a' type='xxxxxxxx' name='xxxxxxxxxxxxx'/>
			<edge id='b' type='fdfdsf' name='zzzzzzzzz' source='a' dest='a'/>
		</diagram>
		<diagram id='x' type='sfadsf'>
			<node id='s' type='yyyyyyyy' name='yyyyyyyyyyyyyy'/>
			<node id='t' type='yyyyyyyy' name='kkkkkkkkkkkkkk'/>
			<edge id='d' type='fdfdsf' name='zzzfdsafdsf' source='x' dest='s'/>
		</diagram>
	</diagrams>
</project>
